const meta = {
  introduction: 'Introduction',
  'data-types': 'Data Types',
  operators: 'Operators',
  constraints: 'Constraints',
  'data-definition-language': 'Data Definition Language',
  'data-manipulation-language': 'Data Manipulation Language',
  'data-query-language': 'Data Query Language',
  'data-control-language': 'Data Control Language',
  'transaction-control-language': 'Transaction Control Language',
  joins: 'Joins',
  'aggregate-functions': 'Aggregate Functions',
  'string-functions': 'String Functions',
  'numeric-functions': 'Numeric Functions',
  'date-and-time-functions': 'Date and Time Functions',
  'conditional-functions': 'Conditional Functions',
  'conversion-functions': 'Conversion Functions',
  json: 'JSON',
  subqueries: 'Subqueries',
  'set-operations': 'Set Operations',
  'common-table-expressions': 'Common Table Expressions',
  'window-functions': 'Window Functions',
  views: 'Views',
  indexes: 'Indexes',
  'stored-procedures': 'Stored Procedures',
  'stored-functions': 'Stored Functions',
  triggers: 'Triggers',
  events: 'Events',
  'database-management': 'Database Management',
  'user-and-account-management': 'User and Account Management',
  security: 'Security',
  'transactions-and-locking': 'Transactions and Locking',
  'query-optimization': 'Query Optimization',
  'table-relationships': 'Table Relationships',
  'database-design': 'Database Design',
  'character-sets-and-collations': 'Character Sets and Collations',
  'storage-and-table-features': 'Storage and Table Features',
  partitioning: 'Partitioning',
  'import-and-export': 'Import and Export',
  'information-schema': 'Information Schema',
  'system-commands': 'System Commands',
  'advanced-sql-features': 'Advanced SQL Features',
  architecture: 'Architecture',
  'advanced-data-types': 'Advanced Data Types',
  'full-text-search': 'Full-Text Search',
  'spatial-data': 'Spatial Data',
  replication: 'Replication',
  'high-availability': 'High Availability',
  'backup-and-recovery': 'Backup and Recovery',
  monitoring: 'Monitoring',
  'performance-tuning': 'Performance Tuning',
  administration: 'Administration',
};

export default meta;
